project:
  type: website
  output-dir: docs

website:
  title: "Zhoutong | AI Research Log"
  description: "Notes on LLMs, Post Training, and Recommender Systems."
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/zhoutongfu/
      - icon: github
        href: https://github.com/zhoutongfu
  sidebar:
    style: "floating"
    contents: auto

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right